package rs2321;

/*
 * rs2321.java
 *
 *
 */
import java.io.*;

/**
 *
 * @author Administrador
 */
public class rs2321 extends javax.swing.JFrame {

    WriterPort emisor;
    ReaderPort reader;
    String a = "";
    int ed,z=0;
    char r;

    /**
     * Creates new form rs2321
     */
    public rs2321() {

        initComponents();

        this.emisor = WriterPort.getInstance();
        this.reader = ReaderPort.getInstance();

        this.reader.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionEventPort actionEventPort = (ActionEventPort) evt;
                evento_de_Lectura(actionEventPort);
            }
        });



    }

    public void evento_de_Lectura(ActionEventPort actionEventPort) {

        a = a + actionEventPort.getReaded();
//area1.setText(area1.getText() + a+ "\n");
//a="";
        ed = a.length();

  for (int i = 0; i < ed; i++) {

            r = a.charAt(i);

            if (r=='@'){
                z=i;
            }else if (r == '#') {
                //area1.setText("");
                area1.setText(area1.getText() + a.substring(z+1,i) + "\n");
                a= "" ;
            }
         }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_enviar = new javax.swing.JButton();
        caja1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plantilla Comunicación RS-232");
        getContentPane().setLayout(null);

        boton_enviar.setText("Enviar");
        boton_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_enviar);
        boton_enviar.setBounds(30, 70, 80, 30);
        getContentPane().add(caja1);
        caja1.setBounds(220, 70, 160, 30);

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 230, 80, 30);

        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 170, 180, 150);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 132, 340, 10);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transmisión de Datos Puerto Serie COM9");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 330, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Recepción Datos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 144, 140, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-417)/2, (screenSize.height-383)/2, 417, 383);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        a = "";
        area1.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void boton_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_enviarActionPerformed


        try {

            String datos;
            datos = caja1.getText();
            char a = (char) (13); // Ejemplo de como enviar caracteres especiales por el puerto
            emisor.escribir("@" +datos+ "#" );

            caja1.setText("");


        } catch (IOException iOException) {
        }

// TODO add your handling code here:
    }//GEN-LAST:event_boton_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new rs2321().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JButton boton_enviar;
    private javax.swing.JTextField caja1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
